# Profile information
name: Mãe Natureza
title: Mãe Natureza
description: > # this means to ignore newlines until "baseurl:"
  Mãe Natureza
#permalink: '/'
root: "/" # the subpath of your site, e.g. /blog
url: "maenatureza.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: ggarciabas@googlemail.com #your-email@domain.com

# Comments
comments: true
discus-identifier: "maenatureza" # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Analytics
#analytics:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
